### ISSUE TITLE
Not working with Xcode 7.3.1 !

### ISSUE THREAD

**Issue by indrajitsinh** [marmelroy/FileBrowser#11]
Display just blank screen and below warning 

2016-06-28 20:52:04.797 FIleBrowserDemo[2533:43383] Warning: Attempt to present <FileBrowser.FileBrowser: 0x7fbe4b849a00> on <FIleBrowserDemo.ViewController: 0x7fbe4a5a9230> whose view is not in the window hierarchy!

![simulator screen shot 28-jun-2016 8 53 58 pm](https://cloud.githubusercontent.com/assets/11308777/16421410/7cac8e74-3d72-11e6-9816-9acc3f004c95.png)

import UIKit
import FileBrowser

class ViewController: UIViewController {
    
    let fileBrowser = FileBrowser()
    override func viewDidLoad() {
        super.viewDidLoad()
 
        self.presentViewController(fileBrowser, animated: true, completion: nil)
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}

**Comment by marmelroy** [comment]
Hi @indrajitsinh, I believe you are trying to present too early. As the error says, the view is not yet in the hierarchy when ViewDidLoad is called. You should present the file browser at a later view controller delegate (e.g. viewDidAppear) or in reaction to a button press.

Hope that helps, 
Roy
