### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by mihailsalari** [marmelroy/FileBrowser#16]
Please update to Swift 3

**Comment by jitsengupta** [comment]
Yes I would ditto this - I am trying to integrate FileBrowser to a project that is already updated to Swift 3 and I am having a really difficult time - getting all these error messages about a missing FileBrowser-Swift.h file etc. Had no problem building with Swift 2.2 and XCode 7. Now everything is broken. Great going Apple!

**Comment by mihailsalari** [comment]
I updated to Swift 3 but author rejected my pull request.

**Comment by marmelroy** [comment]
It wasn't rejected @mihailsalari, just took a bit of time to review. It's released now.
