### ISSUE TITLE
Alot of error in XCode 7.3.1

### ISSUE THREAD

**Issue by matheusjkweber** [marmelroy/FileBrowser#19]
I am getting 46 issues on XCode 7.3.1, it is not compatible anymore?

![filebrowser](https://cloud.githubusercontent.com/assets/15331222/18860674/edf60900-8455-11e6-8a73-dde4b763b6bf.png)

**Comment by marmelroy** [comment]
Hi @matheusjkweber, 

The latest release of FileBrowser is written in Swift 3.0 .

You can continue using the Swift 2.2 version of FileBrowser (it's version Release 0.1.4).
