### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by matheusjkweber** [marmelroy/FileBrowser#20]
It is working for swift 3?

I am getting this errors on XCode 8.

![filebrowser](https://cloud.githubusercontent.com/assets/15331222/19137218/a047f8d6-8b48-11e6-84bd-621ffcd58313.png)

**Comment by marmelroy** [comment]
Yes it is. If installing via cocoapods, please make sure you are using the pre-release version of Cocoapods and that the "Use Legacy Swift Version" in your build setting is set to NO.
