### ISSUE TITLE
use of unresolved identifier 'present'

### ISSUE THREAD

**Issue by uknowmeright** [marmelroy/FileBrowser#21]
I am getting "use of unresolved identifier 'present'" error when i copy the code verbatim from the example:

```
let fileBrowser = FileBrowser()
present(file, animated: true, completion: nil)
```

Am I doing something wrong?
I am also importing the library at top of file and have run pod install

**Comment by marmelroy** [comment]
Thanks @uknowmeright. Indeed, there was a typo there. Fixed with https://github.com/marmelroy/FileBrowser/commit/dbf76445598777e74aa77414f975634dfa375190

**Comment by uknowmeright** [comment]
It is still giving me the "use of unresolved identifier 'present'". As if the function does not exist at all. Any Ideas?

**Comment by uknowmeright** [comment]
I am using swift 2.3 on XCode 8 btw and pulling in version 0.1.4

**Comment by marmelroy** [comment]
FileBrowser 0.1.4 is no longer supported. 

the present function was called presentViewController in Swift 2.3

**Comment by uknowmeright** [comment]
Ah, my bad. Didn't realize you had already updated to Swift 3.0. Thanks for the quick response!
