### ISSUE TITLE
Xcode error: Cannot call value of non-function type 'module<FileManager>'. What am I doing wrong?

### ISSUE THREAD

**Issue by bogdankosh** [marmelroy/FileBrowser#23]
When I try to use FileBrowser and try to create FileBrowser as suggested in README like this: `let fileBrowser = FileBrowser()` I get an error: **Cannot call value of non-function type 'module<FileManager>'**. Importing FileBrowser gives a warning: **File 'ViewController.swift' is part of module 'FileBrowser'; ignoring import**. Am I missing something fundamentally important?

**Comment by marmelroy** [comment]
Hi @bogdankosh, I will need some more details to help. Did you install with Cocoapods / Carthage / manually? Which version of FileBrowser? What version of Swift does your app run (2.3 or 3.0)?

**Comment by bogdankosh** [comment]
Hi, @marmelroy. FileBrowser v 0.2.0, installed with Cocoapods, Swift 3.0 (Xcode 8.1)

**Comment by marmelroy** [comment]
Is your app's name FileBrowser? 🤔

**Comment by bogdankosh** [comment]
@marmelroy That's exactly what it is, tried with different name and it worked. Many thanks and really sorry to bother you with those dumb questions. Best of luck.

**Comment by marmelroy** [comment]
No worries 😄
