### ISSUE TITLE
how to hide tab bar when using tabBarController and present fileBrowser

### ISSUE THREAD

**Issue by kundanjadhav** [marmelroy/FileBrowser#30]
Please help

PFA 
![simulator screen shot jun 16 2017 5 20 56 pm](https://user-images.githubusercontent.com/5459578/27225519-36ace5b6-52b8-11e7-91cf-e76f83e33591.png)

**Comment by aboutsajjad** [comment]
I have the same problem have you found any solution?

**Comment by kundanjadhav** [comment]
Yes. Just hideBottomBar when you push QLPreviewController
