### ISSUE TITLE
Can the file browser also include the size of the file?

### ISSUE THREAD

**Issue by pzearfoss** [marmelroy/FileBrowser#5]
I'm considering using this in an app for debugging purposes while in the while.  One of the key things is being able to see the size of the files.  I wanted to check to see if you had plans to do this.  If not, it's probably something I can extend easily enough.  I could code it up if you're interested.

**Comment by marmelroy** [comment]
Hey @pzearfoss! I agree that file size could be very useful but I'm not sure if it's for everyone... 

However, I just pushed an update that adds a fileAttributes property on FBFile and provides easy access to all the relevant attributes (created at, file size etc). Extending it to do what you want should be pretty straightforward...

**Comment by pzearfoss** [comment]
Thanks, we'll maintain a fork I suppose.
