### ISSUE TITLE
Lost actual file extension

### ISSUE THREAD

**Issue by muukii** [marmelroy/FileBrowser#9]
It looks like the same file exists.

![simulator screen shot mar 24 2016 2 49 10 pm](https://cloud.githubusercontent.com/assets/1888355/14009528/1a753c58-f1d0-11e5-9a83-7f7bd2a91b5c.png)

Actual:

<img width="268" alt="screen shot 2016-03-24 at 2 50 16 pm" src="https://cloud.githubusercontent.com/assets/1888355/14009527/1a7071d2-f1d0-11e5-997b-2f5f9663b09a.png">

**Comment by marmelroy** [comment]
Thanks @muukii. Good find. Fixed with release 0.1.4.

**Comment by muukii** [comment]
@marmelroy Thank you!
